### PR TITLE
Fix CODEOWNERS

### PR DESCRIPTION
**Pull request by josecelano**
- Fix the team name.
- Define responsible maintainers for reviewing workflow changes.

### CODE REVIEW

**Comment by da2ce7** [comment]
Hello José,

With the Codeowners file, who and where is it defined the restrictions of editing the codeowners file itself?

**Comment by josecelano** [comment]
> Hello José, With the Codeowners file, who and where is it defined the restrictions of editing the codeowners file itself?
> […](#)
> Am 3/6/2022 um 15:53 schrieb Jose Celano ***@***.***>: ﻿ @josecelano requested your review on: #239 Fix CODEOWNERS. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because your review was requested.

I do not know.

The [documentation says](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners):

> People with admin or owner permissions can set up a CODEOWNERS file in a repository.

But you can have a different CODEOWNERS file on each branch. I suppose it's a kind of hardcoded protection rule for all branches. If you want to try I've created this test repo: https://github.com/josecelano-test/codeowners-test and added you as maintainer.

**Review by yeraydavidrodriguez — APPROVED** [review]

**Comment by josecelano** [comment]
I've merged it in order to update the team name, but we have to find out what happens if a person with "write" permissions (not being ADMIN or repo OWNER) tries to update the file.

**Comment by josecelano** [comment]
hi @da2ce7 , @yeraydavidrodriguez was able to push changes directly. So basically I suppose it only works for PRs. If you have "write" permission, you can change it. I suppose it's only a kind of warning to include some reviewers before merging PRs. That's all.

**Pull request merged**
