### PR TITLE
Issue 24: add ajv and lodash.isequal

### PR DESCRIPTION
**Pull request by da2ce7**
Extracted New Dependencies from https://github.com/Nautilus-Cyberneering/git-queue/pull/118

### CODE REVIEW

**Comment by josecelano** [comment]
hi @da2ce7,

1. Finally, we are not going to use that dependency. We decided to implement our own function. It's very simple. It does not worth it to add a new dependency. We have to remove it in the [PR](https://github.com/Nautilus-Cyberneering/git-queue/pull/118).
2. Question. Why did you want to extract it to a different PR?

**Comment by da2ce7** [comment]
@josecelano I extracted it because the `lodash.isequal` dependency was mixed into the middle of the pull-request commit series.

I feel like it is a good practice for New Dependencies, Or Dependency Updates, to get their own independent Sign-Off.

**Comment by josecelano** [comment]
> @josecelano I extracted it because the `lodash.isequal` dependency was mixed into the middle of the pull-request commit series.
> 
> I feel like it is a good practice for New Dependencies, Or Dependency Updates, to get their own independent Sign-Off.

OK. I also think is a good practice for dependency updates, but in this case, the dependency was a new dependency that we needed for the new feature (although we finally discarded it).

In general, for New dependencies, I would also do it if we want to add it regardless of the change in the PR, for example: a new development tool, etcetera.

**Comment by da2ce7** [comment]
@josecelano In general, I think that should have he aim where **every commit in a pull request**, not just **every pull request**, passes the full CI tests:

When we integrate a new dependency, or upgrade dependencies, each indivisible dependency change (update, remove, add) should have it's own commit should including:

- Updated `package.json` file.
- Updated `yarn.lock`
- Regenerated `dist` directory.
- Updated documentation, if needed.
- Minimal changes to the code to accommodate the change in the dependencies.

For dependency updates: Like you did with: https://github.com/Nautilus-Cyberneering/git-queue/pull/133, it is good pratice to group multiple updates into a single pull request to a more simple review process and still, every commit in that pull request should each pass the CI tests.

**Comment by josecelano** [comment]
> @josecelano In general, I think that should have he aim where **every commit in a pull request**, not just **every pull request**, passes the full CI tests:
> 

Agree 100% on this.

> When we integrate a new dependency, or upgrade dependencies, each indivisible dependency change (update, remove, add) should have it's own commit should including:
> 
> * Updated `package.json` file.
> * Updated `yarn.lock`
> * Regenerated `dist` directory.
> * Updated documentation, if needed.
> * Minimal changes to the code to accommodate the change in the dependencies.
> 
> For dependency updates: Like you did with: #133, it is good pratice to group multiple updates into a single pull request to a more simple review process and still, every commit in that pull request should each pass the CI tests.

Now I understand. I thought you wanted a different PR for the new dependency and it did not make any sense to me. You only want an independent commit in the feature branch only for adding the new dependency. That's totally fine for me. We can add also this good practice to this issue https://github.com/Nautilus-Cyberneering/git-queue/issues/136

I'm going to close the issue since we do not need that dependency anymore.

**Pull request closed without merging**
